### ISSUE TITLE
sjva.me 회원가입

### ISSUE THREAD

**Issue by mtps1964** [soju6jan/SJVA2#6]
SJVA2 사용을 간절히 원하는데 회원가입을 해야만 사용 할수 있다고 해서 염치 없지만 여기까지 찾아와서 부탁 드립니다.

**Comment by soju6jan** [comment]
클리앙 쪽지로 id / 임시비번 / 성함 / 이메일 알려주세요.

**Comment by dsyun** [comment]
안녕하세요. 후원을 했음에도 계정이 삭제되었는데, 무슨 문제가 있는건가요?
